language: python

sudo: false

python:
  - "3.5"

env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py34-django18
  - TOX_ENV=py35-django18

  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django19
  - TOX_ENV=py35-django19

  - TOX_ENV=py27-django110
  - TOX_ENV=py34-django110
  - TOX_ENV=py35-django110

  - TOX_ENV=py27-djangomaster
  - TOX_ENV=py34-djangomaster
  - TOX_ENV=py35-djangomaster

cache:
  - pip

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
